
spring:
  application:
    name: Inbox App
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.7d120d2b16c87a00
            client-secret: 
  data:
    cassandra:
      keyspace-name: main
      username: WPFRTtEWzZAROosGKarkavTH
      password: 
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
        
astra:
  db:
    id: ea00f25a-aac2-488c-b646-8828a3edc8ee-1
    region: us-east1
    keyspace: main
    application:
      token: 
    
datastax.astra:
  secure-connect-bundle: secure-connect-inbox-app2.zip
  
